services:
    # kafka-ui:
    #     ports:
    #         - 8080:8080
    #     environment:
    #         DYNAMIC_CONFIG_ENABLED: true
    #         KAFKA_CLUSTERS_0_NAME: local
    #         KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    #         KAFKA_CLUSTERS_0_METRICS_PORT: 9991
    #         # KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085
    #         # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
    #         # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083

    # zookeeper:
    #     environment:
    #         - ZOOKEEPER_SERVER_ID=1
    #         - ZOOKEEPER_CLIENT_PORT=2181
    #         - ZOOKEEPER_TICK_TIMES=2000
    #         - ZOOKEEPER_SYNC_LIMIT=2
    #     ports:
    #         - 2181:2181
    # kafka:
    #     ports:
    #         - 9092:9092
    #         - 29092:29092
    #     healthcheck:
    #         test: nc -z localhost 9092 || exit -1
    #         interval: 10s
    #         retries: 5
    #         start_period: 20s
    #     environment:
    #         KAFKA_BROKER_ID: 1
    #         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #         KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    #         KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #         KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #         KAFKA_JMX_PORT: 9991

    # schemaregistry:
    #     ports:
    #         - 8085:8085
    #     environment:
    #         SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    #         SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    #         SCHEMA_REGISTRY_HOST_NAME: schemaregistry
    #         SCHEMA_REGISTRY_LISTENERS: http://schemaregistry:8085

    #         SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
    #         SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
    #         SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas

    # kafka-connect:
    #     ports:
    #         - 8083:8083
    #     environment:
    #         CONNECT_BOOTSTRAP_SERVERS: kafka:29092
    #         CONNECT_GROUP_ID: compose-connect-group
    #         CONNECT_CONFIG_STORAGE_TOPIC: _connect_configs
    #         CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
    #         CONNECT_OFFSET_STORAGE_TOPIC: _connect_offset
    #         CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
    #         CONNECT_STATUS_STORAGE_TOPIC: _connect_status
    #         CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    #         CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
    #         CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schemaregistry:8085
    #         CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
    #         CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schemaregistry:8085
    #         CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    #         CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    #         CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
    #         CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"

    indentity-db:
        environment:
            MYSQL_ROOT_PASSWORD: 1234A
        ports:
            - "5199:3306"

    product-db-1:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes:
            - /d/Dataset/extract/json/:/data/json/
        ports:
            - 27017:27017

    product-db-2:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes:
            - /d/Dataset/extract/json/:/data/json/
        ports:
            - 27018:27017

    product-db-3:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes:
            - /d/Dataset/extract/json/:/data/json/
        ports:
            - 27019:27017

    mongo-express:
        environment:
            - ME_CONFIG_MONGODB_SERVER=product-db-1
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=1234
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=123456
        ports:
            - 8081:8081

    identity-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Logging__Loglevel__Default=Debug
            - Logging__Loglevel__Microsoft.AspNetCore=Debug 
            - Jwt__Issuer=http://identity-api
            - Jwt__Audience=http://identity-api
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - ConnectionStrings__IdentityDb=Server=indentity-db;Database=wksy.identity;User Id=root;Password=1234A;
            - Kafka__ProducerConfig__BootstrapServers=kafka:29092 
            - Kafka__ConsumerConfig__BootstrapServers=kafka:29092 
            - PATH_BASE=/identity-api
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        ports:
            - "5101:80"

    employee-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Jwt__Issuer=http://identity-api
            - Jwt__Audience=http://identity-api
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Kestrel__Endpoints__gRPC__Url=http://0.0.0.0:81
            - ConnectionStrings__EmployeeDb=Server=indentity-db;Database=wksy.employee;User Id=root;Password=1234A;
            - Kafka__ProducerConfig__BootstrapServers=kafka:29092 
            - Kafka__ConsumerConfig__BootstrapServers=kafka:29092 
            - PATH_BASE=/employee-api
        ports:
            - "5102:80"

    product-api-1:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Kestrel__Endpoints__gRPC__Url=http://0.0.0.0:81
            - ProductDatabase__ConnectionString=mongodb://admin:1234@product-db-1:27017
            - ProductDatabase__DatabaseName=product
            - PATH_BASE=/product-api
        ports:
            - "5103:80"

    product-api-2:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Kestrel__Endpoints__gRPC__Url=http://0.0.0.0:81
            - ProductDatabase__ConnectionString=mongodb://admin:1234@product-db-2:27017
            - ProductDatabase__DatabaseName=product
            - PATH_BASE=/product-api
        ports:
            - "5104:80"

    product-api-3:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Kestrel__Endpoints__gRPC__Url=http://0.0.0.0:81
            - ProductDatabase__ConnectionString=mongodb://admin:1234@product-db-3:27017
            - ProductDatabase__DatabaseName=product
            - PATH_BASE=/product-api
        ports:
            - "5105:80"

    productaggregate-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - ProductDatabase__ConnectionString=mongodb://admin:1234@product-db-1:27017
            - ProductDatabase__DatabaseName=wksy
            - PATH_BASE=/product-api
        ports:
            - "5110:80"

    web-apigateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - Logging__Loglevel__Default=Debug
            - Logging__Loglevel__Microsoft.AspNetCore=Debug 
            - Jwt__Issuer=http://identity-api
            - Jwt__Audience=http://identity-api
            - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
            - Reverseproxy__Clusters__identity__Destinations__default__Address=http://identity-api
            - Reverseproxy__Clusters__employee__Destinations__default__Address=http://employee-api
            - Urls__Identity=http://identity-api
            - Urls__Employee=http://employee-api
            - Urls__GrpcIdentity=http://identity-api:81
            - Urls__GrpcEmployee=http://employee-api:81
        ports:
            - "5100:80"

    # fluent-bit:
    #     environment:
    #         # - FLB_ES_HOST=elasticsearch
    #         # - FLB_ES_PORT=9200
    #         - LOKI_HOST=loki
    #         - LOKI_PORT=3100
    #     volumes:
    #         - ./fluent-bit:/fluent-bit/etc
    #     ports:
    #         - 24224:24224

    # elasticsearch:
    #     mem_limit: 2g
    #     environment:
    #         - discovery.type=single-node
    #     ports:
    #         - 9200:9200
    #         - 9300:9300

    # kibana:
    #     environment:
    #         - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    #     ports:
    #         - 5601:5601
    
    # prometheus:
    #     volumes:
    #         - ./prometheus:/etc/prometheus
    #     expose:
    #         - 9090

    # grafana:
    #     environment:
    #           - GF_SECURITY_ADMIN_USER=admin
    #           - GF_SECURITY_ADMIN_PASSWORD=1234
    #     volumes:
    #         - ./grafana/provisioning/:/etc/grafana/provisioning/
    #     ports:
    #         - 3000:3000